# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpctest.sms.sms_pb2 as sms__pb2


class SmsInterfaceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendNormalSMS = channel.unary_unary(
        '/sms.SmsInterface/SendNormalSMS',
        request_serializer=sms__pb2.SMSRequest.SerializeToString,
        response_deserializer=sms__pb2.SMSReply.FromString,
        )
    self.SendTemplateSMS = channel.unary_unary(
        '/sms.SmsInterface/SendTemplateSMS',
        request_serializer=sms__pb2.TplSMSRequest.SerializeToString,
        response_deserializer=sms__pb2.SMSReply.FromString,
        )
    self.QueryTunnelConfig = channel.unary_unary(
        '/sms.SmsInterface/QueryTunnelConfig',
        request_serializer=sms__pb2.TunnelConfigQuery.SerializeToString,
        response_deserializer=sms__pb2.TunnelReplay.FromString,
        )
    self.UpdateTunnelConfig = channel.unary_unary(
        '/sms.SmsInterface/UpdateTunnelConfig',
        request_serializer=sms__pb2.TunnelConfigUpdate.SerializeToString,
        response_deserializer=sms__pb2.TunnelReplay.FromString,
        )
    self.QuerySmsPriceConfig = channel.unary_unary(
        '/sms.SmsInterface/QuerySmsPriceConfig',
        request_serializer=sms__pb2.SmsPriceConfigQuery.SerializeToString,
        response_deserializer=sms__pb2.SmsPriceReplay.FromString,
        )
    self.UpdateSmsPriceConfig = channel.unary_unary(
        '/sms.SmsInterface/UpdateSmsPriceConfig',
        request_serializer=sms__pb2.SmsPriceConfigUpdate.SerializeToString,
        response_deserializer=sms__pb2.SmsPriceReplay.FromString,
        )
    self.QueryAccountLog = channel.unary_unary(
        '/sms.SmsInterface/QueryAccountLog',
        request_serializer=sms__pb2.AccountLogRequest.SerializeToString,
        response_deserializer=sms__pb2.AccountLogReply.FromString,
        )
    self.QueryDeductionRule = channel.unary_unary(
        '/sms.SmsInterface/QueryDeductionRule',
        request_serializer=sms__pb2.QueryDeductionRuleRequest.SerializeToString,
        response_deserializer=sms__pb2.QueryDeductionRuleReply.FromString,
        )
    self.SetDeductionRule = channel.unary_unary(
        '/sms.SmsInterface/SetDeductionRule',
        request_serializer=sms__pb2.SetDeductionRuleRequest.SerializeToString,
        response_deserializer=sms__pb2.SetDeductionRuleReply.FromString,
        )


class SmsInterfaceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendNormalSMS(self, request, context):
    """发送普通短信
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendTemplateSMS(self, request, context):
    """发送模板短信
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QueryTunnelConfig(self, request, context):
    """查询业务类型与短信通道对应关系（全量）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateTunnelConfig(self, request, context):
    """更新业务类型与短信通道对应关系（全量）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QuerySmsPriceConfig(self, request, context):
    """短信费率查询（全量）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSmsPriceConfig(self, request, context):
    """短信费率更新（全量）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QueryAccountLog(self, request, context):
    """查询扣费记录
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QueryDeductionRule(self, request, context):
    """查询扣费方式
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetDeductionRule(self, request, context):
    """设置扣费方式
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SmsInterfaceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendNormalSMS': grpc.unary_unary_rpc_method_handler(
          servicer.SendNormalSMS,
          request_deserializer=sms__pb2.SMSRequest.FromString,
          response_serializer=sms__pb2.SMSReply.SerializeToString,
      ),
      'SendTemplateSMS': grpc.unary_unary_rpc_method_handler(
          servicer.SendTemplateSMS,
          request_deserializer=sms__pb2.TplSMSRequest.FromString,
          response_serializer=sms__pb2.SMSReply.SerializeToString,
      ),
      'QueryTunnelConfig': grpc.unary_unary_rpc_method_handler(
          servicer.QueryTunnelConfig,
          request_deserializer=sms__pb2.TunnelConfigQuery.FromString,
          response_serializer=sms__pb2.TunnelReplay.SerializeToString,
      ),
      'UpdateTunnelConfig': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTunnelConfig,
          request_deserializer=sms__pb2.TunnelConfigUpdate.FromString,
          response_serializer=sms__pb2.TunnelReplay.SerializeToString,
      ),
      'QuerySmsPriceConfig': grpc.unary_unary_rpc_method_handler(
          servicer.QuerySmsPriceConfig,
          request_deserializer=sms__pb2.SmsPriceConfigQuery.FromString,
          response_serializer=sms__pb2.SmsPriceReplay.SerializeToString,
      ),
      'UpdateSmsPriceConfig': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSmsPriceConfig,
          request_deserializer=sms__pb2.SmsPriceConfigUpdate.FromString,
          response_serializer=sms__pb2.SmsPriceReplay.SerializeToString,
      ),
      'QueryAccountLog': grpc.unary_unary_rpc_method_handler(
          servicer.QueryAccountLog,
          request_deserializer=sms__pb2.AccountLogRequest.FromString,
          response_serializer=sms__pb2.AccountLogReply.SerializeToString,
      ),
      'QueryDeductionRule': grpc.unary_unary_rpc_method_handler(
          servicer.QueryDeductionRule,
          request_deserializer=sms__pb2.QueryDeductionRuleRequest.FromString,
          response_serializer=sms__pb2.QueryDeductionRuleReply.SerializeToString,
      ),
      'SetDeductionRule': grpc.unary_unary_rpc_method_handler(
          servicer.SetDeductionRule,
          request_deserializer=sms__pb2.SetDeductionRuleRequest.FromString,
          response_serializer=sms__pb2.SetDeductionRuleReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sms.SmsInterface', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
