# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snowid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snowid.proto',
  package='snowid',
  syntax='proto3',
  serialized_pb=_b('\n\x0csnowid.proto\x12\x06snowid\"\'\n\x15GenerateSnowidRequest\x12\x0e\n\x06uniqId\x18\x01 \x01(\x03\"F\n\x13GenerateSnowidReply\x12\x0f\n\x07\x65rrCode\x18\x01 \x01(\x03\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x03\x32X\n\x06snowid\x12N\n\x0egenerateSnowid\x12\x1d.snowid.GenerateSnowidRequest\x1a\x1b.snowid.GenerateSnowidReply\"\x00\x62\x06proto3')
)




_GENERATESNOWIDREQUEST = _descriptor.Descriptor(
  name='GenerateSnowidRequest',
  full_name='snowid.GenerateSnowidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uniqId', full_name='snowid.GenerateSnowidRequest.uniqId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=63,
)


_GENERATESNOWIDREPLY = _descriptor.Descriptor(
  name='GenerateSnowidReply',
  full_name='snowid.GenerateSnowidReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errCode', full_name='snowid.GenerateSnowidReply.errCode', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='snowid.GenerateSnowidReply.errMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='snowid.GenerateSnowidReply.result', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['GenerateSnowidRequest'] = _GENERATESNOWIDREQUEST
DESCRIPTOR.message_types_by_name['GenerateSnowidReply'] = _GENERATESNOWIDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateSnowidRequest = _reflection.GeneratedProtocolMessageType('GenerateSnowidRequest', (_message.Message,), dict(
  DESCRIPTOR = _GENERATESNOWIDREQUEST,
  __module__ = 'snowid_pb2'
  # @@protoc_insertion_point(class_scope:snowid.GenerateSnowidRequest)
  ))
_sym_db.RegisterMessage(GenerateSnowidRequest)

GenerateSnowidReply = _reflection.GeneratedProtocolMessageType('GenerateSnowidReply', (_message.Message,), dict(
  DESCRIPTOR = _GENERATESNOWIDREPLY,
  __module__ = 'snowid_pb2'
  # @@protoc_insertion_point(class_scope:snowid.GenerateSnowidReply)
  ))
_sym_db.RegisterMessage(GenerateSnowidReply)



_SNOWID = _descriptor.ServiceDescriptor(
  name='snowid',
  full_name='snowid.snowid',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=137,
  serialized_end=225,
  methods=[
  _descriptor.MethodDescriptor(
    name='generateSnowid',
    full_name='snowid.snowid.generateSnowid',
    index=0,
    containing_service=None,
    input_type=_GENERATESNOWIDREQUEST,
    output_type=_GENERATESNOWIDREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SNOWID)

DESCRIPTOR.services_by_name['snowid'] = _SNOWID

# @@protoc_insertion_point(module_scope)
