# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='user',
  syntax='proto3',
  serialized_pb=_b('\n\nuser.proto\x12\x04user\"E\n\x08\x43\x61rdInfo\x12\x0c\n\x04\x61\x63No\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\x03\x12\r\n\x05phone\x18\x04 \x01(\t\"\x9e\x01\n\x1a\x42\x61tchOpenActualCardRequest\x12\x0e\n\x06uniqId\x18\x01 \x01(\x03\x12\x0b\n\x03\x62id\x18\x02 \x01(\x03\x12\r\n\x05\x61\x63\x62Id\x18\x03 \x01(\x03\x12\x0c\n\x04\x63\x63id\x18\x04 \x01(\x03\x12\x0b\n\x03sid\x18\x05 \x01(\x03\x12\x0c\n\x04qrid\x18\x06 \x01(\t\x12\x0c\n\x04type\x18\x07 \x01(\x03\x12\x1d\n\x05users\x18\x08 \x03(\x0b\x32\x0e.user.CardInfo\"K\n\x18\x42\x61tchOpenActualCardReply\x12\x0f\n\x07\x65rrCode\x18\x01 \x01(\x03\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x08\x32\x61\n\x04user\x12Y\n\x13\x62\x61tchOpenActualCard\x12 .user.BatchOpenActualCardRequest\x1a\x1e.user.BatchOpenActualCardReply\"\x00\x62\x06proto3')
)




_CARDINFO = _descriptor.Descriptor(
  name='CardInfo',
  full_name='user.CardInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acNo', full_name='user.CardInfo.acNo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='user.CardInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='user.CardInfo.gender', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='user.CardInfo.phone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=89,
)


_BATCHOPENACTUALCARDREQUEST = _descriptor.Descriptor(
  name='BatchOpenActualCardRequest',
  full_name='user.BatchOpenActualCardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uniqId', full_name='user.BatchOpenActualCardRequest.uniqId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bid', full_name='user.BatchOpenActualCardRequest.bid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acbId', full_name='user.BatchOpenActualCardRequest.acbId', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ccid', full_name='user.BatchOpenActualCardRequest.ccid', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sid', full_name='user.BatchOpenActualCardRequest.sid', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qrid', full_name='user.BatchOpenActualCardRequest.qrid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='user.BatchOpenActualCardRequest.type', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='users', full_name='user.BatchOpenActualCardRequest.users', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=250,
)


_BATCHOPENACTUALCARDREPLY = _descriptor.Descriptor(
  name='BatchOpenActualCardReply',
  full_name='user.BatchOpenActualCardReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errCode', full_name='user.BatchOpenActualCardReply.errCode', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='user.BatchOpenActualCardReply.errMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='user.BatchOpenActualCardReply.result', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=327,
)

_BATCHOPENACTUALCARDREQUEST.fields_by_name['users'].message_type = _CARDINFO
DESCRIPTOR.message_types_by_name['CardInfo'] = _CARDINFO
DESCRIPTOR.message_types_by_name['BatchOpenActualCardRequest'] = _BATCHOPENACTUALCARDREQUEST
DESCRIPTOR.message_types_by_name['BatchOpenActualCardReply'] = _BATCHOPENACTUALCARDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CardInfo = _reflection.GeneratedProtocolMessageType('CardInfo', (_message.Message,), dict(
  DESCRIPTOR = _CARDINFO,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.CardInfo)
  ))
_sym_db.RegisterMessage(CardInfo)

BatchOpenActualCardRequest = _reflection.GeneratedProtocolMessageType('BatchOpenActualCardRequest', (_message.Message,), dict(
  DESCRIPTOR = _BATCHOPENACTUALCARDREQUEST,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.BatchOpenActualCardRequest)
  ))
_sym_db.RegisterMessage(BatchOpenActualCardRequest)

BatchOpenActualCardReply = _reflection.GeneratedProtocolMessageType('BatchOpenActualCardReply', (_message.Message,), dict(
  DESCRIPTOR = _BATCHOPENACTUALCARDREPLY,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.BatchOpenActualCardReply)
  ))
_sym_db.RegisterMessage(BatchOpenActualCardReply)



_USER = _descriptor.ServiceDescriptor(
  name='user',
  full_name='user.user',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=329,
  serialized_end=426,
  methods=[
  _descriptor.MethodDescriptor(
    name='batchOpenActualCard',
    full_name='user.user.batchOpenActualCard',
    index=0,
    containing_service=None,
    input_type=_BATCHOPENACTUALCARDREQUEST,
    output_type=_BATCHOPENACTUALCARDREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['user'] = _USER

# @@protoc_insertion_point(module_scope)
